aws_dbt_snowflake_project:
  outputs:
    dev:
      account: ULUQYKG-WY99196
      database: AIRBNB
      password: ix76BwgFsuQCr9N
      role: ACCOUNTADMIN
      schema: dbt_schema
      threads: 1
      type: snowflake
      user: BIANCA
      warehouse: COMPUTE_WH
  target: dev
